[build]
  command = "npm install && npm run build:dev"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.5.0"
  NPM_VERSION = "10.0.0"
  NODE_ENV = "development"
  VITE_APP_ENV = "development"

# Development site settings
[dev]
  command = "npm run dev"
  port = 5174
  publish = "dist"

# Support client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# More relaxed headers for development
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """
      default-src 'self' 'unsafe-inline' 'unsafe-eval';
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.googleapis.com https://maps.googleapis.com https://api.openai.com http://localhost:* ws://localhost:*;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.googleapis.com https://maps.googleapis.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*.googleapis.com;
      font-src 'self' data: https://fonts.gstatic.com;
      img-src 'self' data: https://*.googleapis.com https://*.gstatic.com https://images.unsplash.com https://*.unsplash.com blob:;
      frame-src 'self' https://*.supabase.co https://*.googleapis.com https://*.google.com;
      worker-src 'self' blob:;
    """
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, content-type, Authorization, apikey, X-Client-Info"

# Enable development-specific features
[context.development]
  environment = { NODE_ENV = "development", VITE_ENABLE_DEBUG_LOGS = "true", VITE_ENABLE_TEST_FEATURES = "true" }

[functions]
  node_bundler = "esbuild" 