[auth]
enable_signup = true
site_url = "http://localhost:5174"
additional_redirect_urls = ["http://localhost:5174", "http://localhost:5174/reset-password"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.user-service]
enabled = true
verify_jwt = false
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/user-service/index.ts"

[functions.admin-service]
enabled = true
verify_jwt = true
entrypoint = "./functions/admin-service/index.ts"

[functions.partner-service]
enabled = true
verify_jwt = true
entrypoint = "./functions/partner-service/index.ts"

[functions.billing-service]
enabled = true
verify_jwt = true
entrypoint = "./functions/billing-service/index.ts"

[functions.ai-service]
enabled = true
verify_jwt = true
entrypoint = "./functions/ai-service/index.ts"


