[auth]
enable_signup = true
site_url = "http://localhost:5174"
additional_redirect_urls = ["http://localhost:5174", "http://localhost:5174/reset-password"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.client-registration]
enabled = true
verify_jwt = true
import_map = "./functions/client-registration/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/client-registration/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/client-registration/*.html" ]

[functions.send-invitation]
enabled = true
verify_jwt = true
import_map = "./functions/send-invitation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-invitation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-invitation/*.html" ]

[functions.user-service]
enabled = true
verify_jwt = false
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/user-service/index.ts"

[functions.admin-service]
enabled = true
verify_jwt = true
entrypoint = "./functions/admin-service/index.ts"

[functions.partner-service]
enabled = true
verify_jwt = true
entrypoint = "./functions/partner-service/index.ts"

[functions.billing-service]
enabled = true
verify_jwt = true
entrypoint = "./functions/billing-service/index.ts"
