#!/bin/bash

# Test script for Galileo Report Builder endpoints
# Usage: ./test-endpoints.sh [base_url]

BASE_URL=${1:-"http://localhost:8789"}

echo "🧪 Testing Galileo Report Builder endpoints..."
echo "📍 Base URL: $BASE_URL"
echo ""

# Test health endpoint
echo "🏥 Testing health endpoint..."
curl -s "$BASE_URL/health" | jq '.' || echo "❌ Health check failed"
echo ""

# Test root endpoint  
echo "📝 Testing root endpoint..."
curl -s "$BASE_URL/" | jq '.' || echo "❌ Root endpoint failed"
echo ""

# Test PDF generation endpoint
echo "📄 Testing PDF generation..."
PDF_REQUEST='{
  "html": "<html><head><title>Test</title></head><body><h1>Test PDF Document</h1><p>This is a test PDF generated by the Galileo Report Builder service.</p></body></html>",
  "filename": "test-report.pdf",
  "options": {
    "format": "Letter",
    "printBackground": true
  }
}'

curl -X POST "$BASE_URL/api/generate-pdf" \
  -H "Content-Type: application/json" \
  -d "$PDF_REQUEST" \
  --output test-output.pdf \
  --write-out "HTTP %{http_code} - %{size_download} bytes downloaded\n" \
  || echo "❌ PDF generation failed"

if [ -f "test-output.pdf" ]; then
  echo "✅ PDF generated successfully: $(ls -lh test-output.pdf | awk '{print $5}')"
  file test-output.pdf
else
  echo "❌ PDF file not created"
fi

echo ""
echo "🧪 Test completed!"

# Cleanup
rm -f test-output.pdf